In [46]:
from pylab import *

def init_map_s(size):
    global t_gue 
    global inf
    global isol
    global t_echan
    t_echan = 0.5
    isol = 0.3
    inf = 0.15
    t_gue = 7
    map = array([np.random.uniform(low = 0.0, high = 0.0, size = size) for i in range(size)])
    return map

def init_map(size):
    global t_gue 
    global inf
    global isol
    isol = 0.2
    inf = 0.15
    t_gue = 7
    map = array([np.random.uniform(low = 0.0, high = 0.0, size = size) for i in range(size)])
    map[np.random.choice(size - 1)][np.random.choice(size - 1)] = 1
    return map

def evolution(map,size):
    for i in range(size):
        for j in range(size):
            if map[i][j] > 0:
                map[i][j] = map[i][j] + 1
                if map[i][j] == t_gue:
                    map[i][j] = -1
            elif map[i][j] < -1:
                map[i][j] = map[i][j] - 1
                if map[i][j] == t_gue * -1:
                    map[i][j] = -1
    return map

def infection(map,size):
    for i in range(size):
        for j in range(size):
            if map[i][j] > 0:
                try:
                    if map[i + 1][j] == 0 and i != size - 1:
                        map[i + 1][j] = np.random.binomial(1, inf, 1)
                except:
                    pass
                try:
                    if map[i - 1][j] == 0 and i != 0:
                        map[i - 1][j] = np.random.binomial(1, inf, 1)
                except:
                    pass
                try:
                    if map[i][j + 1] == 0 and j != size - 1:
                         map[i][j + 1] = np.random.binomial(1, inf, 1)
                except:
                    pass
                try:
                    if map[i][j - 1] == 0 and j != 0:
                        map[i][j - 1] = np.random.binomial(1, inf, 1)
                except:
                    pass
    return map

def isolate(map,size):
    for i in range(size):
        for j in range(size):
            if map[i][j] > 0:
                if np.random.binomial(1, isol, 1) == 1:
                    map[i][j] = map[i][j] * -1
    return map

def check(map,size):
    c = 1
    for i in range(size):
        for j in range(size):
            if map[i][j] != 0 and map[i][j] != -1:
                c = 0
    return c

def echange(map,map2,size,size2):
    if np.random.binomial(1, t_echan, 1) == 1:
        x1 = np.random.choice(size)
        y1 = np.random.choice(size)
        x2 = np.random.choice(size2)
        y2 = np.random.choice(size2)
        temp = map[x1][y1]
        map[x1][y1] = map2[x2][y2]
        map2[x2][y2] = temp
    return map,map2
    
size = 10
size2 = 10
i = 0
m = init_map(size)
m2 = init_map_s(size2)
while(check(m,size) == 0 or check(m2,size2) == 0):
    m = evolution(m,size)
    m = infection(m,size)
    m = isolate(m,size)
    m2 = evolution(m2,size2)
    m2 = infection(m2,size2)
    m2 = isolate(m2,size2)
    m,m2 = echange(m,m2,size,size2)
    i = i + 1
print(m)
print(m2)
print(i)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
6
